const skillsArray  = [
    'Teaching',
    'Mentoring',
    'Tutoring',
    'Data Entry',
    'Event Planning',
    'Fundraising',
    'Community Outreach',
    'Public Speaking',
    'Social Media Management',
    'Graphic Design',
    'Web Development',
    'Writing and Editing',
    'Photography',
    'Videography',
    'Marketing',
    'First Aid',
    'CPR',
    'Conflict Resolution',
    'Leadership',
    'Project Management',
  ];
export default skillsArray ;  