export const sampleEventData = [
    {
      name: "Event 1",
      location: "Location 1",
      password: "Password 1",
      start_date: "2023-10-15",
      end_date: "2023-10-16",
      skills_required: ["Skill1", "Skill2"],
      event_poster: "1.png",
      categories: ["Category1", "Category2"],
      description: "Description for Event 1",
      organizer: {
        name: "Organizer 1",
        organizer: true,
        email: "organizer1@example.com",
        pincode: "12345",
        phone_no: "123-456-7890",
        skills: ["Skill1", "Skill2"],
        profile_phpto: "Profile1.jpg",
        interests: ["Interest1", "Interest2"],
      }
    },
    {
      name: "Event 2",
      location: "Location 2",
      password: "Password 2",
      start_date: "2023-11-20",
      end_date: "2023-11-21",
      skills_required: ["Skill3", "Skill4"],
      event_poster: "2.png",
      categories: ["Category2", "Category3"],
      description: "Description for Event 2",
      organizer: {
        name: "Organizer 2",
        organizer: true,
        email: "organizer2@example.com",
        pincode: "54321",
        phone_no: "987-654-3210",
        skills: ["Skill3", "Skill4"],
        profile_phpto: "Profile2.jpg",
        interests: ["Interest2", "Interest3"],
      }
    },
    {
      name: "Event 3",
      location: "Location 3",
      password: "Password 3",
      start_date: "2023-12-25",
      end_date: "2023-12-26",
      skills_required: ["Skill2", "Skill5"],
      event_poster: "3.png",
      categories: ["Category1", "Category3"],
      description: "Description for Event 3",
      organizer: {
        name: "Organizer 3",
        organizer: true,
        email: "organizer3@example.com",
        pincode: "98765",
        phone_no: "555-123-4567",
        skills: ["Skill2", "Skill5"],
        profile_phpto: "Profile3.jpg",
        interests: ["Interest3", "Interest4"],
      }
    },
    {
      name: "Event 4",
      location: "Location 4",
      password: "Password 4",
      start_date: "2024-01-30",
      end_date: "2024-01-31",
      skills_required: ["Skill1", "Skill3"],
      event_poster: "4.png",
      categories: ["Category2", "Category4"],
      description: "Description for Event 4",
      organizer: {
        name: "Organizer 4",
        organizer: true,
        email: "organizer4@example.com",
        pincode: "54321",
        phone_no: "987-654-3210",
        skills: ["Skill1", "Skill3"],
        profile_phpto: "Profile4.jpg",
        interests: ["Interest1", "Interest3"],
      }
    },
    {
      name: "Event 5",
      location: "Location 5",
      password: "Password 5",
      start_date: "2024-02-10",
      end_date: "2024-02-11",
      skills_required: ["Skill4", "Skill5"],
      event_poster: "5.png",
      categories: ["Category3", "Category4"],
      description: "Description for Event 5",
      organizer: {
        name: "Organizer 5",
        organizer: true,
        email: "organizer5@example.com",
        pincode: "12345",
        phone_no: "123-456-7890",
        skills: ["Skill4", "Skill5"],
        profile_phpto: "Profile5.jpg",
        interests: ["Interest4", "Interest5"],
      }
    },
    {
      name: "Event 6",
      location: "Location 6",
      password: "Password 6",
      start_date: "2024-03-15",
      end_date: "2024-03-16",
      skills_required: ["Skill1", "Skill2"],
      event_poster: "6.png",
      categories: ["Category1", "Category4"],
      description: "Description for Event 6",
      organizer: {
        name: "Organizer 6",
        organizer: true,
        email: "organizer6@example.com",
        pincode: "98765",
        phone_no: "555-123-4567",
        skills: ["Skill1", "Skill2"],
        profile_phpto: "Profile6.jpg",
        interests: ["Interest1", "Interest2"],
      }
    },
    {
      name: "Event 7",
      location: "Location 7",
      password: "Password 7",
      start_date: "2024-04-20",
      end_date: "2024-04-21",
      skills_required: ["Skill3", "Skill5"],
      event_poster: "7.png",
      categories: ["Category2", "Category3"],
      description: "Description for Event 7",
      organizer: {
        name: "Organizer 7",
        organizer: true,
        email: "organizer7@example.com",
        pincode: "54321",
        phone_no: "987-654-3210",
        skills: ["Skill3", "Skill5"],
        profile_phpto: "Profile7.jpg",
        interests: ["Interest3", "Interest4"],
      }
    },
    {
      name: "Event 8",
      location: "Location 8",
      password: "Password 8",
      start_date: "2024-05-25",
      end_date: "2024-05-26",
      skills_required: ["Skill2", "Skill4"],
      event_poster: "8.png",
      categories: ["Category1", "Category2"],
      description: "Description for Event 8",
      organizer: {
        name: "Organizer 8",
        organizer: true,
        email: "organizer8@example.com",
        pincode: "12345",
        phone_no: "123-456-7890",
        skills: ["Skill2", "Skill4"],
        profile_phpto: "Profile8.jpg",
        interests: ["Interest2", "Interest4"],
      }
    },
    {
      name: "Event 9",
      location: "Location 9",
      password: "Password 9",
      start_date: "2024-06-30",
      end_date: "2024-06-31",
      skills_required: ["Skill1", "Skill5"],
      event_poster: "9.png",
      categories: ["Category3", "Category4"],
      description: "Description for Event 9",
      organizer: {
        name: "Organizer 9",
        organizer: true,
        email: "organizer9@example.com",
        pincode: "98765",
        phone_no: "555-123-4567",
        skills: ["Skill1", "Skill5"],
        profile_phpto: "Profile9.jpg",
        interests: ["Interest1", "Interest5"],
      }
    },
    {
      name: "Event 10",
      location: "Location 10",
      password: "Password 10",
      start_date: "2024-07-05",
      end_date: "2024-07-06",
      skills_required: ["Skill2", "Skill3"],
      event_poster: "10.jpg",
      categories: ["Category1", "Category2"],
      description: "Description for Event 10",
      organizer: {
        name: "Organizer 10",
        organizer: true,
        email: "organizer10@example.com",
        pincode: "54321",
        phone_no: "987-654-3210",
        skills: ["Skill2", "Skill3"],
        profile_phpto: "Profile10.jpg",
        interests: ["Interest2", "Interest3"],
      }
    },
  ];
  
 
  